### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by EvelienVerbeeck** [EvelienVerbeeck/Startspeler#4]

**Comment by BradSpanjaard** [comment]
Met de code in het word bestand kan je op deze website https://dbdiagram.io/d het ERD schema aanmaken 
[Code_ERD_StartSpeler.docx](https://github.com/EvelienVerbeeck/Startspeler/files/6199813/Code_ERD_StartSpeler.docx)

**Comment by BradSpanjaard** [comment]
![image](https://user-images.githubusercontent.com/72517239/112368933-e5704a00-8cdb-11eb-930a-f4b55f75fef3.png)

**Comment by Follower30** [comment]
Ik was dit nog juist aan het denken. Dat de persoon ook nog een atribuut  "TotaalPrijsDrankkaarten" Waarbij de prijzen van betaalde drankkaarten worden opgeteld. Deze moest de manager ook nog zien. Voor de rest ziet het er goed uit!

**Comment by BradSpanjaard** [comment]
Doormiddel van een databaseoperation kunnen we dit opvragen

**Comment by Follower30** [comment]
![ClasDiagram](https://user-images.githubusercontent.com/73027569/112379946-0db27580-8ce9-11eb-8192-de758fcad303.png)
