### ISSUE TITLE
Usecasediagrammen

### ISSUE THREAD

**Issue by EvelienVerbeeck** [EvelienVerbeeck/Startspeler#7]

**Comment by EvelienVerbeeck** [comment]
![startspelerUsecaseDia](https://user-images.githubusercontent.com/72517290/111339258-e8ce5a80-8677-11eb-9a0c-4624f6dd8c56.png)

**Comment by BradSpanjaard** [comment]
![Usecase_Brad](https://user-images.githubusercontent.com/72517239/111354185-52556580-8686-11eb-9781-da9bb7d1aff4.png)

**Comment by Follower30** [comment]
![UseCase startspeler](https://user-images.githubusercontent.com/73027569/111363255-1a532000-8690-11eb-85d3-594b7df23d65.png)

**Comment by Follower30** [comment]
![Uploading UseCase startspeler.png…]()

**Comment by Follower30** [comment]
![UseCase startspeler](https://user-images.githubusercontent.com/73027569/112523312-ee761f80-8d9e-11eb-8ffc-fcd746639b77.png)
